/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Atendente;
import fatec.poo.model.Hospede;
import fatec.poo.model.QuartoHotel;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas Roseira && Marcelo Zapatta
 */
public class GuiReservaLiberacaoQuarto extends javax.swing.JFrame {

    /**
     * Creates new form GuiCadastroCliente
     */
    public GuiReservaLiberacaoQuarto(ArrayList<Hospede> h,
            ArrayList<Atendente> a, ArrayList<QuartoHotel> q) {
        initComponents();
        this.setLocationRelativeTo(null);
        hospede = h;
        atendente = a;
        quartoHotel = q;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollBar1 = new javax.swing.JScrollBar();
        lblRegFuncional0 = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        txtCpfHospede = new javax.swing.JTextField();
        txtRegFuncional = new javax.swing.JTextField();
        lblNomeHospede = new javax.swing.JLabel();
        btnPesquisarQuarto = new javax.swing.JButton();
        lblNumQuarto = new javax.swing.JLabel();
        txtNumeroQuarto = new javax.swing.JTextField();
        lblDataEntrada = new javax.swing.JLabel();
        txtDataEntrada = new javax.swing.JTextField();
        lblDataSaida = new javax.swing.JLabel();
        txtDataSaida = new javax.swing.JTextField();
        btnReservar = new javax.swing.JButton();
        btnLiberar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnPesquisarHospede = new javax.swing.JButton();
        lblNomeAtendente = new javax.swing.JLabel();
        lblValorPagar0 = new javax.swing.JLabel();
        lblSituacao0 = new javax.swing.JLabel();
        lblValorAPagar = new javax.swing.JLabel();
        lblSituacao = new javax.swing.JLabel();
        btnPesquisarAtendente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reserva/Liberação Quarto");
        setResizable(false);

        lblRegFuncional0.setText("Reg. Func.");

        lblCPF.setText("CPF Hospede");

        txtCpfHospede.setEnabled(false);
        txtCpfHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfHospedeActionPerformed(evt);
            }
        });

        txtRegFuncional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegFuncionalActionPerformed(evt);
            }
        });

        lblNomeHospede.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnPesquisarQuarto.setText("...");
        btnPesquisarQuarto.setEnabled(false);
        btnPesquisarQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarQuartoActionPerformed(evt);
            }
        });

        lblNumQuarto.setText("No. Quarto");

        txtNumeroQuarto.setEnabled(false);

        lblDataEntrada.setText("Data Entrada");

        txtDataEntrada.setEnabled(false);

        lblDataSaida.setText("Data Saída");

        txtDataSaida.setEnabled(false);

        btnReservar.setText("Reservar");
        btnReservar.setEnabled(false);
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        btnLiberar.setText("Liberar");
        btnLiberar.setEnabled(false);
        btnLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnPesquisarHospede.setText("...");
        btnPesquisarHospede.setEnabled(false);
        btnPesquisarHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarHospedeActionPerformed(evt);
            }
        });

        lblNomeAtendente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblValorPagar0.setText("Valor a Pagar");

        lblSituacao0.setText("Situação");

        lblValorAPagar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblSituacao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnPesquisarAtendente.setText("...");
        btnPesquisarAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarAtendenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCPF)
                    .addComponent(lblRegFuncional0)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValorPagar0)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(btnPesquisarQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                                .addComponent(lblSituacao0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumeroQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblValorAPagar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                        .addComponent(txtDataSaida, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDataEntrada, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtRegFuncional, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnPesquisarAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtCpfHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnPesquisarHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblNomeHospede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblNomeAtendente, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(lblDataSaida)
                    .addComponent(lblDataEntrada)
                    .addComponent(lblNumQuarto))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReservar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLiberar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRegFuncional0)
                        .addComponent(txtRegFuncional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesquisarAtendente)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCPF)
                        .addComponent(txtCpfHospede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesquisarHospede))
                    .addComponent(lblNomeHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNumQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNumeroQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPesquisarQuarto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblValorAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblValorPagar0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblSituacao0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnReservar)
                    .addComponent(btnLiberar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCpfHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfHospedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfHospedeActionPerformed

    private void txtRegFuncionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegFuncionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegFuncionalActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnPesquisarAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarAtendenteActionPerformed
        int x;
        for (x = 0; x < atendente.size(); x++) {
            if (atendente.get(x) instanceof Atendente) {
                if (((Atendente) atendente.get(x)).getRegFunc().equals(txtRegFuncional.getText())) {
                    break;
                }
            }
        }

        if (x < atendente.size()) {
            posAtendente = x; //localizou o objeto Hospede no ArrayList
        } else {
            posAtendente = -1;//não localizou o objeto Hospede no ArrayList
        }

        if (posAtendente >= 0) {
            lblNomeAtendente.setText(atendente.get(posAtendente).getNome());

            txtRegFuncional.setEnabled(false);
            btnPesquisarAtendente.setEnabled(false);

            txtCpfHospede.setEnabled(true);
            btnPesquisarHospede.setEnabled(true);
            txtCpfHospede.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Atendente não cadastrado");
        }
        
        txtCpfHospede.setText(null);
        txtDataEntrada.setText(null);
        txtDataSaida.setText(null);
        txtNumeroQuarto.setText(null);
        lblValorAPagar.setText(null);
        lblSituacao.setText(null);
    }//GEN-LAST:event_btnPesquisarAtendenteActionPerformed

    private void btnPesquisarHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarHospedeActionPerformed
        int x;

        for (x = 0; x < hospede.size(); x++) {
            if (hospede.get(x) instanceof Hospede) {
                if (((Hospede) hospede.get(x)).getCpf().equals(txtCpfHospede.getText())) {
                    break;
                }
            }
        }

        if (x < hospede.size()) {
            posHospede = x; //localizou o objeto Hospede no ArrayList
        } else {
            posHospede = -1;//não localizou o objeto Hospede no ArrayList
        }

        if (posHospede >= 0) {
            lblNomeHospede.setText(hospede.get(posHospede).getNome());

            txtCpfHospede.setEnabled(false);
            btnPesquisarHospede.setEnabled(false);

            if (hospede.get(posHospede).getQuartoHotel() instanceof QuartoHotel) {
                txtNumeroQuarto.setText(String.valueOf(hospede.get(posHospede).getQuartoHotel().getNumQuarto()));
                txtDataEntrada.setText(hospede.get(posHospede).getQuartoHotel().getDataEntrada());
                lblSituacao.setText("Ocupado");

                txtDataSaida.setEnabled(true);
                txtDataSaida.requestFocus();
                btnLiberar.setEnabled(true);
            } else {
                txtNumeroQuarto.setEnabled(true);
                btnPesquisarQuarto.setEnabled(true);

                txtNumeroQuarto.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Hóspede não cadastrado");
        }
    }//GEN-LAST:event_btnPesquisarHospedeActionPerformed

    private void btnPesquisarQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarQuartoActionPerformed
        int x;
        for (x = 0; x < quartoHotel.size(); x++) {
            if (quartoHotel.get(x) instanceof QuartoHotel) {
                if (((QuartoHotel) quartoHotel.get(x)).getNumQuarto() == (Integer.parseInt(txtNumeroQuarto.getText()))) {
                    break;
                }
            }
        }

        if (x < quartoHotel.size()) {
            lblSituacao.setText("Livre");
            posQuartoHotel = x; // localizou o objeto QuartoHotel no ArrayList
        } else {
            posQuartoHotel = -1; // não localizou o objeto QuartoHotel no ArrayList
        }

        if (posQuartoHotel >= 0) {
            if (!quartoHotel.get(x).getSituacao()) {
                lblNomeHospede.setText(hospede.get(posHospede).getNome());

                txtNumeroQuarto.setEnabled(false);
                btnPesquisarQuarto.setEnabled(false);

                txtDataEntrada.setEnabled(true);
                btnReservar.setEnabled(true);

                txtDataEntrada.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Quarto ocupado");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Quarto não cadastrado");
        }
    }//GEN-LAST:event_btnPesquisarQuartoActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        QuartoHotel quartoHotelReserva = quartoHotel.get(posQuartoHotel);
        quartoHotelReserva.setDataEntrada(txtDataEntrada.getText());
        quartoHotelReserva.reservar((Hospede) hospede.get(posHospede), (Atendente) atendente.get(posAtendente));
        
        lblSituacao.setText(null);
        btnReservar.setEnabled(false);
        txtDataEntrada.setEnabled(false);
        txtDataEntrada.setText(null);

        txtRegFuncional.setEnabled(true);

        txtRegFuncional.setText(null);
        txtCpfHospede.setText(null);
        txtNumeroQuarto.setText(null);

        lblNomeAtendente.setText(null);
        lblNomeHospede.setText(null);
        btnPesquisarAtendente.setEnabled(true);

        txtRegFuncional.requestFocus(true);
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        DecimalFormat df = new DecimalFormat("#,##0.00");
        
        Calendar data1 = Calendar.getInstance();
        Calendar data2 = Calendar.getInstance();
        
        int quantidadeDias;
        double valorAPagar;
        
        QuartoHotel quarto = quartoHotel.get(posQuartoHotel);

        try {                
            // Converte uma string no dd/mm/aaaa para 
            // um objeto da classe Calendar
            data1.setTime(sdf.parse(txtDataEntrada.getText()));
            data2.setTime(sdf.parse(txtDataSaida.getText()));
        } catch (java.text.ParseException e) {
            JOptionPane.showMessageDialog(this, "Data inválida.");
        }

        quantidadeDias = data2.get(Calendar.DAY_OF_YEAR) - data1.get(Calendar.DAY_OF_YEAR);

        valorAPagar = quarto.liberar(quantidadeDias, hospede.get(posHospede).getTxDesconto());
        
        lblValorAPagar.setText(df.format(valorAPagar));
        
        lblSituacao.setText("Livre");
        btnLiberar.setEnabled(false);
        btnPesquisarAtendente.setEnabled(true);
        txtRegFuncional.setEnabled(true);
        txtRegFuncional.requestFocus(true);
        txtDataSaida.setEnabled(false);
    }//GEN-LAST:event_btnLiberarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLiberar;
    private javax.swing.JButton btnPesquisarAtendente;
    private javax.swing.JButton btnPesquisarHospede;
    private javax.swing.JButton btnPesquisarQuarto;
    private javax.swing.JButton btnReservar;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblDataEntrada;
    private javax.swing.JLabel lblDataSaida;
    private javax.swing.JLabel lblNomeAtendente;
    private javax.swing.JLabel lblNomeHospede;
    private javax.swing.JLabel lblNumQuarto;
    private javax.swing.JLabel lblRegFuncional0;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JLabel lblSituacao0;
    private javax.swing.JLabel lblValorAPagar;
    private javax.swing.JLabel lblValorPagar0;
    private javax.swing.JTextField txtCpfHospede;
    private javax.swing.JTextField txtDataEntrada;
    private javax.swing.JTextField txtDataSaida;
    private javax.swing.JTextField txtNumeroQuarto;
    private javax.swing.JTextField txtRegFuncional;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Hospede> hospede;
    private ArrayList<Atendente> atendente;
    private ArrayList<QuartoHotel> quartoHotel;
    private int posAtendente;
    private int posHospede;
    private int posQuartoHotel;
}
